# Generated by Django 4.0 on 2021-12-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['titulo'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posteos'},
        ),
    ]
