# Generated by Django 4.0 on 2021-12-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
