# Generated by Django 4.0 on 2021-12-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
